### ISSUE TITLE
More documentation for Katalon integration for mobile test automation

### ISSUE THREAD

**Issue by georific** [kobiton/samples#22]
The section **Run automation test on Kobiton devices using Katalon tool** is this referencing running automated test for CI? If so, are more complete example of how to use Katalon and kobiton in CI for test automation?

I am able to successfully run katalon test using kobiton devices, however it is very much a manually process.  I have to upload the APK then select kobiton devices before running the tests.  How are these steps automated? 

How do I  dynamically upload the APK (Seems to be an API for this) and assign the `Start application` to the proper URL and select favorite device.

**Comment by tritruongkobiton** [comment]
Hi Customer,

We do have the sample to illustrate detail steps showing how to integrate Kobiton Apps Repository with CI tool as below:

https://github.com/kobiton/GitHub-Jenkins-KobitonAppsRepo-Appium-CI-CD/tree/master/Integrate_Kobiton_Apps_Repository_with_CI_tool

You can use it to generate appID and append with your Katalon integration.
Kindly take a look and let me know if you have any questions.

Best,
Tri

**Comment by georific** [comment]
@tritruongkobiton 
Thanks this helps! however I am not sure I understand what you mean by 

> append with your Katalon integration

Thanks

**Comment by tritruongkobiton** [comment]
Hi Customer,

I mean that you can catch the generated appID and use it in your Katalon script.
For more information how to do it, kindly contact Katalon support: https://forum.katalon.com/categories/mobile-testing

Best,
Tri

**Comment by georific** [comment]
Thanks, just in case anyone else needs this you must add all of the Kobiton integration under the Katalon Studio -> preferences -> Katalon ->kobiton.  Next, use the command line builder in Katalon to run your test against the kobiton cloud devices.

https://docs.katalon.com/display/KD/Console+Mode+Execution
